// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJVLGk5T4_f8KbpLgPNUBww8ON389p0_Q',
    appId: '1:515001320241:web:4eba621af97d8fc98a2610',
    messagingSenderId: '515001320241',
    projectId: 'bookmarkllm',
    authDomain: 'bookmarkllm.firebaseapp.com',
    storageBucket: 'bookmarkllm.appspot.com',
    measurementId: 'G-VC24BKB7QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz6FQgZy5o3aUA9umDi7vXHqLJW1qG4fg',
    appId: '1:515001320241:android:8366a40077ac4b678a2610',
    messagingSenderId: '515001320241',
    projectId: 'bookmarkllm',
    storageBucket: 'bookmarkllm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdUBfIxsYTfwhAR4BJ1_06-ZLRW0fX0q0',
    appId: '1:515001320241:ios:cb449d76bd994ed48a2610',
    messagingSenderId: '515001320241',
    projectId: 'bookmarkllm',
    storageBucket: 'bookmarkllm.appspot.com',
    iosBundleId: 'com.example.bookmarkLlm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdUBfIxsYTfwhAR4BJ1_06-ZLRW0fX0q0',
    appId: '1:515001320241:ios:cb449d76bd994ed48a2610',
    messagingSenderId: '515001320241',
    projectId: 'bookmarkllm',
    storageBucket: 'bookmarkllm.appspot.com',
    iosBundleId: 'com.example.bookmarkLlm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJVLGk5T4_f8KbpLgPNUBww8ON389p0_Q',
    appId: '1:515001320241:web:ba38df538c58823b8a2610',
    messagingSenderId: '515001320241',
    projectId: 'bookmarkllm',
    authDomain: 'bookmarkllm.firebaseapp.com',
    storageBucket: 'bookmarkllm.appspot.com',
    measurementId: 'G-HHQSKVZ1GR',
  );
}
